name: andy kuny
title: andy kuny
description: >
  The personal website of Andy Kuny.
about: >
  The personal website of Andy Kuny.
author: Andy Kuny

master_repo: false
url: 'https://www.andykuny.com'
markdown: kramdown
highlighter: rouge

paginate: 5

logo:
disqus_shortname:

rtl: false
owner:
  name: Andy Kuny
  avatar:
  email: hi@andykuny.com
  github: https://github.com/akuny

google_analytics:
google_verify:
bing_verify: