name: andy kuny
title: andy kuny
description: >
  Another wretched blog.
about: >
  The personal website of Andy Kuny.
author: Andy Kuny

master_repo: false
url: 'https://www.andykuny.com'
markdown: kramdown
highlighter: rouge

plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

paginate: 5

logo:
disqus_shortname:

rtl: false
owner:
  name: Andy Kuny
  avatar:
  email: hi@andykuny.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:
  github: https://github.com/akuny
  stackexchange:
  linkedin: https://www.linkedin.com/in/andy-kuny

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
